[package]
name = "parse_message"
version = "0.1.0"
edition = "2024"
authors = ["okawak <kodak2022@outlook.jp>"]
description = "Parse Discord messages"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
