[package]
name = "html_to_markdown"
version.workspace = true
authors.workspace = true
description = "Parse HTML to Customized Markdown"
edition.workspace = true
repository.workspace = true
license-file.workspace = true

[dependencies]
thiserror.workspace = true
html5ever.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
url.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
rstest.workspace = true
indoc.workspace = true
