[package]
name = "html_to_markdown"
version.workspace = true
authors.workspace = true
description = "Parse HTML to Customized Markdown"
edition.workspace = true
repository.workspace = true

[dependencies]
thiserror = "2"
html5ever = "0.31"

[dev-dependencies]
pretty_assertions = "1"
